def chatbot():					
    faq = {
	"bertanggung jawab": "Sikap bertanggung jawab terhadap reproduksi melibatkan menjaga kebersihan organ reproduksi, menjalani gaya hidup sehat, menghindari perilaku seksual berisiko, melakukan pemeriksaan kesehatan rutin, serta mendapatkan edukasi yang benar mengenai kesehatan dan hak reproduksi. Selain itu, penting untuk melindungi diri dari kekerasan seksual dan menghormati tubuh serta batasan diri dan orang lain.",
	"pengaruh pola makan": "Pola makan sangat mempengaruhi kesehatan reproduksi dengan menyediakan nutrisi penting untuk pembentukan hormon dan fungsi organ reproduksi, serta memengaruhi keseimbangan hormon dan siklus menstruasi. Makanan tinggi lemak trans dan rendah serat dapat mengganggu keseimbangan hormonal dan kesuburan, sementara makanan utuh yang kaya serat, vitamin, dan mineral seperti asam folat dan zat besi mendukung fungsi reproduksi yang sehat.",
	"periksa kesehatan reproduksi": "Periksa kesehatan reproduksi disarankan sejak usia 21 tahun bagi wanita, atau lebih cepat jika sudah aktif secara seksual, untuk deteksi dini penyakit dan kondisi seperti kanker serviks melalui Pap Smear dan skrining Infeksi Menular Seksual (IMS). Bagi pria, pemeriksaan organ intim dianjurkan saat memasuki usia reproduktif, sekitar usia 22-25 tahun atau saat mulai aktif secara seksual atau jika mengalami masalah seperti nyeri atau keputihan abnormal.",
	"contoh alat kontrasepsi": "Contoh alat kontrasepsi meliputi kondom (pria dan wanita), pil KB, suntik KB, KB implan (susuk), IUD (alat kontrasepsi dalam rahim atau spiral), patch KB (koyo KB), diafragma, dan metode sterilisasi seperti vasektomi (MOP) untuk pria dan MOW untuk wanita, serta metode operasi dan hormonal seperti suntik testosteron untuk pria.",
	"penyakit raja singa": "Penyakit yang disebut sebagai 'Raja singa' adalah Sifilis, sebuah penyakit menular seksual (PMS) yang disebabkan oleh infeksi bakteri Treponema pallidum. Penyakit ini ditularkan melalui kontak langsung dengan luka atau cairan tubuh penderita, seperti saat aktivitas seksual (vaginal, oral, atau anal), penggunaan jarum suntik bersama, atau dari ibu ke bayi saat persalinan. Jika tidak diobati, sifilis dapat menyebabkan komplikasi serius yang merusak organ vital seperti otak, jantung, dan bahkan dapat mengancam nyawa.",
	"pubertas": "Pubertas adalah proses alami di mana tubuh anak berubah dari masa kanak-kanak menjadi dewasa, ditandai dengan kematangan seksual, perubahan fisik, dan perkembangan emosional yang dipicu oleh hormon. Proses ini melibatkan perubahan seperti pertumbuhan payudara dan menstruasi pada perempuan, pertumbuhan rambut kemaluan, peningkatan tinggi badan, serta perubahan suara dan organ seks pada laki-laki.",
	"penting memahami proses menstruasi": "Pentingnya memahami proses menstruasi bagi remaja perempuan meliputi menjaga kesehatan reproduksi, mencegah penyakit seperti infeksi saluran reproduksi, mengelola gejala fisik dan emosional seperti nyeri dan fatigue, mempersiapkan diri secara fisik dan mental saat pubertas, serta memiliki kesadaran akan tubuh dan organ reproduksinya untuk pengambilan keputusan yang bertanggung jawab di masa depan.",
	"peran orang tua": "Peran orang tua dan guru dalam edukasi kesehatan reproduksi remaja sangatlah penting; orang tua berperan sebagai pendidik utama dan panutan yang memberikan informasi secara terbuka dan berkelanjutan, sementara guru berperan sebagai pemberi informasi akurat, edukator kesehatan, serta pendukung di sekolah dengan berkolaborasi dengan orang tua dan tenaga kesehatan untuk menciptakan lingkungan belajar yang aman dan informatif.",
	"infeksi menular seksual": "Infeksi Menular Seksual (IMS) adalah infeksi yang ditularkan dari satu orang ke orang lain melalui kontak seksual (vaginal, anal, atau oral) atau melalui cairan tubuh tertentu. IMS dapat disebabkan oleh bakteri, virus, atau parasit, dan meliputi berbagai kondisi seperti HIV, sifilis, gonore, herpes genital, dan HPV. Gejalanya beragam, mulai dari luka pada kelamin, keputihan, nyeri saat buang air kecil, hingga tidak adanya gejala sama sekali, dan dapat berujung pada komplikasi serius seperti infertilitas atau bahkan kanker jika tidak diobati.",
	"kesehatan reproduksi": "Kesehatan reproduksi adalah keadaan sejahtera secara fisik, mental, dan sosial secara utuh, bukan hanya bebas dari penyakit atau kecacatan, yang berkaitan dengan sistem, fungsi, dan proses reproduksi seseorang. Ini berarti bahwa seseorang memiliki kemampuan untuk memiliki kehidupan seksual yang memuaskan dan aman, kemampuan untuk bereproduksi, serta kebebasan untuk memutuskan kapan, apakah, dan seberapa sering mereka ingin memiliki anak tanpa adanya paksaan atau diskriminasi.",
	"menjaga kesehatan": "Menjaga kesehatan organ reproduksi itu penting untuk mencegah penyakit berbahaya seperti infeksi menular seksual (IMS) dan kanker, menjaga kesuburan, dan memastikan kualitas hidup seksual yang sehat. Pemeriksaan rutin, kebersihan diri, gaya hidup sehat, dan menghindari perilaku berisiko juga merupakan cara penting untuk menjaga kesehatan organ reproduksi.",
	"kebersihan organ reproduksi": "Untuk menjaga kebersihan organ reproduksi, lakukan aktivitas pembersihan harian seperti mencuci area genital dengan air mengalir dan sabun lembut, serta ganti pakaian dalam berbahan katun setiap hari. Bagi perempuan, bersihkan dari arah depan ke belakang setelah buang air kecil dan tidak perlu menggunakan sabun pembersih khusus vagina. Bagi laki-laki yang belum disunat, bersihkan area kulup penis dengan menariknya perlahan dan membersihkan di bawah air mengalir.",
	"perilaku reproduksi sehat": "Perilaku reproduksi sehat adalah perilaku yang menunjukkan kepedulian terhadap kesehatan fisik, mental, dan sosial dalam segala aspek yang berhubungan dengan sistem reproduksi, fungsi, serta prosesnya, termasuk seksualitas. Perilaku ini mencakup menjaga kebersihan organ reproduksi, melakukan aktivitas seksual yang aman dan bertanggung jawab, menerapkan gaya hidup sehat, serta memiliki pengetahuan yang memadai tentang kesehatan reproduksi dan seksualitas.",
	"bahaya seks bebas": "Bahaya seks bebas antara lain infeksi menular seksual (IMS) seperti HIV dan gonore, kehamilan tidak diinginkan, gangguan kesehatan mental seperti depresi dan rendahnya harga diri, risiko kesehatan reproduksi seperti infertilitas dan kanker, serta dapat mengganggu pendidikan dan perkembangan diri.",
	"menghindari napza": "Penyalahgunaan narkoba atau alkohol dapat berdampak negatif pada kesehatan reproduksi pria dan wanita. Meskipun penelitian pada manusia masih terbatas, bukti yang ada menunjukkan bahwa penyalahgunaan alkohol dan narkoba dapat mengganggu keseimbangan hormon, mempengaruhi kesuburan, dan menyebabkan disfungsi seksual.",
	"fungsi alat kontrasepsi": "Fungsi utama alat kontrasepsi adalah untuk mencegah kehamilan yang tidak diinginkan dengan cara menghambat pertemuan sel sperma dan sel telur atau menghentikan produksi sel telur. Selain itu, alat kontrasepsi juga berfungsi menjarangkan kehamilan untuk menjaga kesehatan ibu dan bayi, mengatur jarak kelahiran agar sesuai keinginan, mengurangi risiko kematian ibu dan bayi, serta dapat meningkatkan kesejahteraan keluarga.",
	"ganti pakaian": "Pakaian dalam perlu diganti setiap hari untuk mencegah pertumbuhan bakteri, jamur, dan penyebab infeksi kulit, bau tidak sedap, serta iritasi pada area intim, karena pakaian dalam yang telah digunakan akan menampung keringat, sel kulit mati, dan minyak dari tubuh. Mengganti pakaian dalam secara rutin merupakan upaya penting untuk menjaga kebersihan dan kesehatan tubuh secara keseluruhan.",
	"akibat tidak menjaga": "Akibat tidak menjaga kebersihan organ reproduksi termasuk masalah kesuburan (kemandulan), peningkatan risiko penyakit menular seksual (PMS) seperti gonore dan klamidia, serta infeksi bakteri atau jamur yang dapat menyebabkan keputihan tidak normal, gatal, dan bau menyengat. Kondisi ini juga bisa memicu komplikasi kehamilan, gangguan aktivitas seksual, dan penyakit lain seperti infeksi saluran kemih.",
	"perilaku sehat": "Contoh perilaku sehat pada remaja meliputi aktivitas fisik teratur, makan makanan bergizi, tidur cukup, menjaga kebersihan diri dan lingkungan, serta mengelola stres dengan baik. Selain itu, penting untuk membatasi penggunaan gawai, tidak merokok, menghindari narkoba, dan secara rutin memeriksakan kesehatan ke fasilitas kesehatan.",
	"mencegah kehamilan" :"Untuk mencegah kehamilan pada remaja, strategi utama adalah pantang seksual atau tunda kehamilan. Jika sudah aktif secara seksual, metode kontrasepsi yang efektif seperti pil KB, implan, suntik KB, atau penggunaan kondom secara benar dapat digunakan, selain menjaga komunikasi terbuka dengan orang tua dan edukasi kesehatan reproduksi yang komprehensif.",
	"tanda gangguan": "Tanda-tanda gangguan organ reproduksi meliputi nyeri saat buang air kecil atau saat berhubungan seksual, keluarnya cairan abnormal (seperti keputihan berbau atau perdarahan di luar siklus haid) pada wanita, cairan yang keluar dari penis pria, gatal, luka, atau benjolan di area genital, serta perubahan siklus menstruasi.",
	"stress dan kesehatan reproduksi": "Stres yang berlebihan dapat mengganggu sistem hormonal, yang berdampak negatif pada kesuburan, siklus menstruasi, dan fungsi ovarium pada wanita, serta memengaruhi kualitas sperma pada pria. Tingkat stres yang tinggi juga dapat memperburuk kondisi tertentu seperti sindrom ovarium polikistik (PCOS) dan meningkatkan risiko komplikasi kehamilan seperti kelahiran prematur dan berat badan lahir rendah. Hal ini dapat menyebabkan ketidakteraturan menstruasi, mengurangi kesuburan pada pria dan wanita, meningkatkan risiko komplikasi kehamilan (seperti kelahiran prematur), serta memperburuk stres oksidatif dan risiko infeksi vagina.",
	"menjaga pergaulan": "Menjaga pergaulan sangat penting untuk kesehatan reproduksi karena pergaulan yang sehat dan bertanggung jawab akan mencegah kehamilan tidak diinginkan dan infeksi menular seksual (IMS) seperti HIV/AIDS. Informasi yang benar mengenai kesehatan reproduksi juga membekali remaja untuk membuat keputusan bijak, menjaga kebersihan organ reproduksi, dan melindungi diri dari kekerasan seksual.",
	"hak reproduksi": "Remaja perlu mengetahui hak-hak reproduksinya untuk dapat membuat keputusan yang bertanggung jawab atas tubuh dan kesehatan mereka, mencegah kehamilan dini, penularan penyakit menular seksual (PMS), serta kekerasan seksual. Pengetahuan ini juga membantu remaja memahami dan melindungi diri mereka sendiri, membina hubungan yang sehat, dan menjadi pribadi yang lebih berdaya.",
	"dampak psikologis": "Dampak psikologis kehamilan di usia remaja meliputi risiko depresi, kecemasan, rendahnya harga diri, isolasi sosial, dan ketidakstabilan emosi. Remaja sering kali merasa kewalahan, malu, takut, dan bingung karena belum siap menghadapi tanggung jawab sebagai orang tua dan perubahan tubuh. Stigma sosial dan kurangnya dukungan dapat memperburuk kondisi emosional, yang juga dapat memicu perilaku maladaptif seperti menyalahkan diri sendiri atau bahkan tindakan aborsi.",
	"pakaian wanita di iklim tropis": "Bahan yang cocok untuk pakaian dalam di iklim tropis adalah katun, bambu, dan rayon/viscose karena sifatnya yang ringan, menyerap keringat, dan memiliki sirkulasi udara yang baik untuk menjaga kulit tetap sejuk dan sehat. Hindari bahan sintetis tebal seperti poliester penuh yang dapat memerangkap panas.",
	"bahan polyester": "Bahan polyester diketahui dapat menyebabkan alergi dan iritasi kulit karena bahan kimia seperti pewarna dan pemberian bahan anti-kusut dalam produksinya. Gejala ini termasuk gatal-gatal, kemerahan, ruam pada kulit, kulit kering, dan mengelupas. Kulit sensitif akan lebih mudah terpapar risiko ini ketika mengenakan pakaian polyester.",
	"pengaruh pubertas": "Pengaruh pubertas pada organ reproduksi meliputi matangnya organ reproduksi dan siap berfungsi untuk reproduksi, seperti pembesaran testis dan penis pada pria serta perkembangan payudara dan menstruasi pada wanita. Peningkatan produksi hormon reproduksi (testosteron pada pria) memicu perubahan ini dan mempengaruhi kesuburan serta gairah seksual.",
	"persentase": "Tidak ada persentase pasti remaja di Indonesia yang tidak peduli kesehatan reproduksinya, tetapi data menunjukkan pemanfaatan pelayanan kesehatan reproduksi remaja di Indonesia sangat rendah (kurang dari 10%) dan pengetahuan serta perilaku seputar kesehatan reproduksi masih banyak yang kurang. Kurangnya informasi, persepsi negatif terhadap isu reproduksi, serta faktor lingkungan dan sosial menjadi penyebab utama kurangnya kesadaran dan perhatian remaja terhadap kesehatan reproduksinya.",
	"contoh kasus": "Kasus remaja yang tidak peduli kesehatan reproduksinya sering kali menyebabkan kehamilan tidak diinginkan (KTD), aborsi, infeksi menular seksual (IMS), dan pada kasus yang lebih buruk adalah penyebaran HIV/AIDS. Masalah ini berakar dari kurangnya pengetahuan dan informasi, pergeseran perilaku seksual, stigma dan hambatan budaya, serta kurangnya akses ke layanan kesehatan yang ramah remaja."
	
    }

    print("Selamat datang di chatbot FAQ Kesehatan dan Perilaku Reproduksi yang Bertanggung Jawab! Ketik 'keluar' untuk mengakhiri.")
    while True:
        user_input = input("Tanya: ").lower()
        if user_input == "keluar":
            print("Terima kasih telah menggunakan chatbot kami. Sampai jumpa!")
           
            break

        found = False
        for key in faq:
            if key in user_input:
                print("Jawab: " + faq[key])
                found = True
                break

        if not found:
            print("Maaf, saya tidak mengerti pertanyaan Anda. Silakan coba pertanyaan lain.")

if __name__ == "__main__":
    chatbot()